/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://iiuf6bt5dfcchifrul4n775x3i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-535aamt5frhq5gs7fgabxqk6fq",
    "aws_cognito_identity_pool_id": "us-east-2:a9a3633c-f2cf-4fbb-98f0-d1ed08c8e9c2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wHrIAKr1K",
    "aws_user_pools_web_client_id": "2o462dr9iu5onbh99ihat55adb",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
